// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbal

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID
	Userid    string
	Price     float64
	Quantity  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Balance   float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
